Algoritmo "3"

Var
   n1, n2, n3: inteiro
   valor: real
Inicio
   escreval ("Digite o primeiro numero:")
   leia (n1)
   escreval ("Digite o segundo numero:")
   leia (n2)
   escreval ("Digite o terceiro numero:")
   leia (n3)
   valor<-(n1+n2+n3)
   se (valor>=50) entao
      escreval ("A soma dos tres numero é maior que 50!")
   senao
      escreval ("A soma dos tres numeros não é maior que 50!")
   fimse
Fimalgoritmo